/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.testesdeconexao.app;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.mycompany.testesdeconexao.client.Client;

import java.util.Timer;
import java.util.TimerTask;

import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Usuário
 */
public class app extends javax.swing.JFrame {

   String myName;
   int rows, porta;
   Client client;
   
    public app() {
        initComponents();
        this.setBounds(0, 0, 420, 350);
        pn_login.setVisible(true);
        pn_chat.setVisible(false);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_chat = new javax.swing.JPanel();
        txt_escrever = new javax.swing.JTextField();
        btn_enviar_chat = new javax.swing.JButton();
        scrl_pn_chat_box = new javax.swing.JScrollPane();
        txt_area_chat_box = new javax.swing.JTextArea();
        scrl_pn_client_list = new javax.swing.JScrollPane();
        txt_area_client_list = new javax.swing.JTextArea();
        pn_login = new javax.swing.JPanel();
        lb_Title = new javax.swing.JLabel();
        lb_nome = new javax.swing.JLabel();
        lb_porta = new javax.swing.JLabel();
        txt_porta = new javax.swing.JTextField();
        txt_nome = new javax.swing.JTextField();
        bnt_enviar_nome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_chat.setPreferredSize(new java.awt.Dimension(400, 300));
        pn_chat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_escrever.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        txt_escrever.setText("Escrever");
        txt_escrever.setPreferredSize(new java.awt.Dimension(300, 26));
        txt_escrever.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_escreverMouseClicked(evt);
            }
        });
        txt_escrever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_escreverActionPerformed(evt);
            }
        });
        pn_chat.add(txt_escrever, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 270, -1, -1));
        txt_escrever.getAccessibleContext().setAccessibleDescription("");

        btn_enviar_chat.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        btn_enviar_chat.setText("Enviar");
        btn_enviar_chat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_enviar_chat.setPreferredSize(new java.awt.Dimension(85, 26));
        btn_enviar_chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviar_chatActionPerformed(evt);
            }
        });
        pn_chat.add(btn_enviar_chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        scrl_pn_chat_box.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrl_pn_chat_box.setToolTipText("");
        scrl_pn_chat_box.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrl_pn_chat_box.setAutoscrolls(true);
        scrl_pn_chat_box.setFocusable(false);
        scrl_pn_chat_box.setPreferredSize(new java.awt.Dimension(240, 260));

        txt_area_chat_box.setEditable(false);
        txt_area_chat_box.setColumns(20);
        txt_area_chat_box.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        txt_area_chat_box.setLineWrap(true);
        txt_area_chat_box.setRows(1);
        txt_area_chat_box.setWrapStyleWord(true);
        txt_area_chat_box.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_area_chat_box.setMaximumSize(new java.awt.Dimension(390, 99999999));
        txt_area_chat_box.setMinimumSize(new java.awt.Dimension(390, 260));
        scrl_pn_chat_box.setViewportView(txt_area_chat_box);

        pn_chat.add(scrl_pn_chat_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        scrl_pn_client_list.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrl_pn_client_list.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrl_pn_client_list.setPreferredSize(new java.awt.Dimension(145, 260));

        txt_area_client_list.setEditable(false);
        txt_area_client_list.setColumns(20);
        txt_area_client_list.setRows(1);
        txt_area_client_list.setPreferredSize(new java.awt.Dimension(260, 84));
        scrl_pn_client_list.setViewportView(txt_area_client_list);

        pn_chat.add(scrl_pn_client_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 5, -1, -1));

        pn_login.setPreferredSize(new java.awt.Dimension(405, 300));
        pn_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_Title.setFont(new java.awt.Font("Segoe Print", 0, 48)); // NOI18N
        lb_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Title.setText("Meetwo");
        lb_Title.setPreferredSize(new java.awt.Dimension(200, 64));
        pn_login.add(lb_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        lb_nome.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        lb_nome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_nome.setText("Digite seu nome");
        lb_nome.setMaximumSize(new java.awt.Dimension(150, 33));
        lb_nome.setMinimumSize(new java.awt.Dimension(150, 33));
        lb_nome.setPreferredSize(new java.awt.Dimension(150, 33));
        pn_login.add(lb_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 80, -1, -1));

        lb_porta.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        lb_porta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_porta.setText("Digite a porta");
        lb_porta.setMaximumSize(new java.awt.Dimension(150, 33));
        lb_porta.setMinimumSize(new java.awt.Dimension(150, 33));
        lb_porta.setPreferredSize(new java.awt.Dimension(150, 33));
        pn_login.add(lb_porta, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 160, -1, -1));

        txt_porta.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        txt_porta.setMaximumSize(new java.awt.Dimension(200, 26));
        txt_porta.setMinimumSize(new java.awt.Dimension(200, 26));
        txt_porta.setPreferredSize(new java.awt.Dimension(200, 26));
        pn_login.add(txt_porta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        txt_nome.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        txt_nome.setMaximumSize(new java.awt.Dimension(200, 26));
        txt_nome.setMinimumSize(new java.awt.Dimension(200, 26));
        txt_nome.setPreferredSize(new java.awt.Dimension(200, 26));
        pn_login.add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        bnt_enviar_nome.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        bnt_enviar_nome.setText("Enviar");
        bnt_enviar_nome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bnt_enviar_nome.setMaximumSize(new java.awt.Dimension(100, 27));
        bnt_enviar_nome.setMinimumSize(new java.awt.Dimension(100, 27));
        bnt_enviar_nome.setPreferredSize(new java.awt.Dimension(100, 27));
        bnt_enviar_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_enviar_nomeActionPerformed(evt);
            }
        });
        pn_login.add(bnt_enviar_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_login, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pn_chat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pn_chat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_enviar_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_enviar_nomeActionPerformed
        myName = txt_nome.getText();
        porta = Integer.parseInt(txt_porta.getText());
        
        client = new Client("localhost", porta,myName);
        client.sendName(myName);

        pn_login.setVisible(false);
        pn_chat.setVisible(true);
        rows = 1;
        txt_area_client_list.append(myName);

        new Thread(new Runnable() { // espera uma mensgem do servidor
            public void run() {
                while (true) {
                    String message = client.receiveMessage();
                    if (message != null) {
                        SwingUtilities.invokeLater(new Runnable() {
                            public void run() {
                                txt_area_chat_box.append(message + "\n");
                            }
                        });
                    }
                }
            }
        }).start();
    }//GEN-LAST:event_bnt_enviar_nomeActionPerformed

    private void txt_escreverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_escreverMouseClicked
       txt_escrever.setText(" ");
    }//GEN-LAST:event_txt_escreverMouseClicked

    private void btn_enviar_chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviar_chatActionPerformed

        if(txt_escrever.getText().equals("Escrever") || txt_escrever.getText().equals(" ") ){
            txt_escrever.setText("Escrever");
        }else{
            String mensagem = txt_escrever.getText();
            client.sendMessage(mensagem);
            txt_area_chat_box.append(myName+": "+mensagem+"\n");
            txt_escrever.setText("Escrever");
            txt_area_chat_box.setRows(rows++);
        }
    }//GEN-LAST:event_btn_enviar_chatActionPerformed

    private void txt_escreverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_escreverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_escreverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            FlatLightLaf.setup();
            FlatDarkLaf.setup();
            UIManager.put("FlatLaf.darkTheme", true);
            for (UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Dark".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.formdev.flatlaf.intellijthemes.FlatIntelliJLightLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       //</editor-fold>
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app().setVisible(true);
            }
        });
    }

    public void waitFiveSeconds() {
        Timer timer = new Timer();
        TimerTask task = new TimerTask() {
            public void run() {
                // Código a ser executado após 5 segundos
                System.out.println("5 segundos se passaram.");
            }
        };
        timer.schedule(task, 5000); // Agendar a tarefa para ser executada após 5000 milissegundos (5 segundos)
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_enviar_nome;
    private javax.swing.JButton btn_enviar_chat;
    private javax.swing.JLabel lb_Title;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_porta;
    private javax.swing.JPanel pn_chat;
    private javax.swing.JPanel pn_login;
    private javax.swing.JScrollPane scrl_pn_chat_box;
    private javax.swing.JScrollPane scrl_pn_client_list;
    private javax.swing.JTextArea txt_area_chat_box;
    private javax.swing.JTextArea txt_area_client_list;
    private javax.swing.JTextField txt_escrever;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_porta;
    // End of variables declaration//GEN-END:variables
}
